-- MySQL Script generated by MySQL Workbench
-- Wed Mar 13 12:15:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`picture` (
  `picture_id` INT NOT NULL,
  `picture_title` VARCHAR(45) NULL,
  `picture_path` VARCHAR(45) NOT NULL,
  `picture_recipe` INT NOT NULL,
  PRIMARY KEY (`picture_id`),
  INDEX `fk_Picture_Recipe1_idx` (`picture_recipe` ASC) VISIBLE,
  CONSTRAINT `fk_Picture_Recipe1`
    FOREIGN KEY (`picture_recipe`)
    REFERENCES `mydb`.`recipe` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) NOT NULL,
  `auth_key` VARCHAR(32) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `password_reset_token` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `status` SMALLINT(10) NOT NULL,
  `role` INT(11) NOT NULL,
  `created_at` INT(11) NOT NULL,
  `updated_at` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(15) NOT NULL,
  `category_description` VARCHAR(45) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recipe` (
  `recipe_id` INT NOT NULL,
  `recipe_title` VARCHAR(45) NOT NULL,
  `recipe_date` DATE NOT NULL,
  `recipe_owner` INT NOT NULL,
  `recipe_preparation` TEXT NULL,
  `recipe_album` INT NOT NULL,
  `recipe_owner` INT NOT NULL,
  `recipe_category` INT NOT NULL,
  PRIMARY KEY (`recipe_id`),
  UNIQUE INDEX `recipe_title_UNIQUE` (`recipe_title` ASC) VISIBLE,
  INDEX `fk_Recipe_Picture_idx` (`recipe_album` ASC) VISIBLE,
  INDEX `fk_Recipe_User1_idx` (`recipe_owner` ASC) VISIBLE,
  INDEX `fk_Recipe_Category1_idx` (`recipe_category` ASC) VISIBLE,
  CONSTRAINT `fk_Recipe_Picture`
    FOREIGN KEY (`recipe_album`)
    REFERENCES `mydb`.`picture` (`picture_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipe_User1`
    FOREIGN KEY (`recipe_owner`)
    REFERENCES `mydb`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipe_Category1`
    FOREIGN KEY (`recipe_category`)
    REFERENCES `mydb`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ingredient` (
  `ingredient_id` INT NOT NULL,
  `ingredient_name` VARCHAR(15) NOT NULL,
  `ingredient_symbol` VARCHAR(45) NULL,
  PRIMARY KEY (`ingredient_id`),
  UNIQUE INDEX `ingredient_name_UNIQUE` (`ingredient_name` ASC) VISIBLE,
  UNIQUE INDEX `ingredient_symbol_UNIQUE` (`ingredient_symbol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`unit` (
  `unit_id` INT NOT NULL,
  `unit_name` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`unit_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recipe_ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recipe_ingredient` (
  `recipe_ingredient_id` INT NOT NULL,
  `recipe_id` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  `ingredient_quantity` INT NULL,
  `ingredient_unit` INT NOT NULL,
  `ingredient_desc` VARCHAR(15) NULL,
  PRIMARY KEY (`recipe_ingredient_id`),
  INDEX `fk_Recipe_Ingredient_Recipe1_idx` (`recipe_id` ASC) VISIBLE,
  INDEX `fk_Recipe_Ingredient_Ingredient1_idx` (`ingredient_id` ASC) VISIBLE,
  INDEX `fk_Recipe_Ingredient_unit1_idx` (`ingredient_unit` ASC) VISIBLE,
  CONSTRAINT `fk_Recipe_Ingredient_Recipe1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `mydb`.`recipe` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipe_Ingredient_Ingredient1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `mydb`.`ingredient` (`ingredient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipe_Ingredient_unit1`
    FOREIGN KEY (`ingredient_unit`)
    REFERENCES `mydb`.`unit` (`unit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rates` (
  `rate_id` INT NOT NULL,
  `rate_owner` INT NOT NULL,
  `rate_recipe` INT NOT NULL,
  PRIMARY KEY (`rate_id`),
  INDEX `fk_Rates_User1_idx` (`rate_owner` ASC) VISIBLE,
  INDEX `fk_Rates_Recipe1_idx` (`rate_recipe` ASC) VISIBLE,
  CONSTRAINT `fk_Rates_User1`
    FOREIGN KEY (`rate_owner`)
    REFERENCES `mydb`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rates_Recipe1`
    FOREIGN KEY (`rate_recipe`)
    REFERENCES `mydb`.`recipe` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `comment_id` INT NOT NULL,
  `comment` TEXT NOT NULL,
  `comment_owner` INT NOT NULL,
  `comment_recipe` INT NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `fk_Comment_User1_idx` (`comment_owner` ASC) VISIBLE,
  INDEX `fk_Comment_Recipe1_idx` (`comment_recipe` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`comment_owner`)
    REFERENCES `mydb`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Recipe1`
    FOREIGN KEY (`comment_recipe`)
    REFERENCES `mydb`.`recipe` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`like` (
  `like_id` INT NOT NULL,
  `like_owner` INT NOT NULL,
  `like_recipe` INT NOT NULL,
  PRIMARY KEY (`like_id`),
  INDEX `fk_Like_User1_idx` (`like_owner` ASC) VISIBLE,
  INDEX `fk_Like_Recipe1_idx` (`like_recipe` ASC) VISIBLE,
  CONSTRAINT `fk_Like_User1`
    FOREIGN KEY (`like_owner`)
    REFERENCES `mydb`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Like_Recipe1`
    FOREIGN KEY (`like_recipe`)
    REFERENCES `mydb`.`recipe` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auth_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_rule` (
  `name` VARCHAR(64) NOT NULL,
  `data` BLOB NULL,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auth_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_item` (
  `name` VARCHAR(64) NOT NULL,
  `type` SMALLINT NOT NULL,
  `description` TEXT NULL,
  `data` BLOB NULL,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  `rule_name` VARCHAR(64) NULL,
  PRIMARY KEY (`name`),
  INDEX `fk_auth_item_auth_rule1_idx` (`rule_name` ASC) VISIBLE,
  CONSTRAINT `fk_auth_item_auth_rule1`
    FOREIGN KEY (`rule_name`)
    REFERENCES `mydb`.`auth_rule` (`name`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auth_item_child`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_item_child` (
  `parent` VARCHAR(64) NOT NULL,
  `child` VARCHAR(64) NOT NULL,
  INDEX `fk_auth_item_child_auth_item1_idx` (`parent` ASC) VISIBLE,
  INDEX `fk_auth_item_child_auth_item2_idx` (`child` ASC) VISIBLE,
  CONSTRAINT `fk_auth_item_child_auth_item1`
    FOREIGN KEY (`parent`)
    REFERENCES `mydb`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_auth_item_child_auth_item2`
    FOREIGN KEY (`child`)
    REFERENCES `mydb`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auth_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_assignment` (
  `item_name` VARCHAR(64) NOT NULL,
  `user_id` VARCHAR(64) NOT NULL,
  `created_at` INT NULL,
  INDEX `fk_auth_assignment_idx` (`item_name` ASC) VISIBLE,
  CONSTRAINT `fk_auth_assignment`
    FOREIGN KEY (`item_name`)
    REFERENCES `mydb`.`auth_item` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) NOT NULL,
  `auth_key` VARCHAR(32) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `password_reset_token` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `status` SMALLINT(10) NOT NULL,
  `role` INT(11) NOT NULL,
  `created_at` INT(11) NOT NULL,
  `updated_at` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
